// ===== Phase 4: 日记自动生成服务 =====
// 查询当日 focus_sessions + todo_items → 生成 Markdown 模板
// 保存到 %APPDATA%/moefocus/sums/YYYY-MM-DD.md
// Phase 5: 配合 GitService 自动 commit+push

import { DatabaseService } from './DatabaseService'
import { join } from 'path'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { app } from 'electron'

export class DiaryService
{
  static generate(date: string): { file_path: string; content: string }
  {
    const db = DatabaseService.instance

    // Get focus sessions for the date
    const sessions = db.all(
      `SELECT fs.*, COALESCE(t.title, fs.subject) as display_subject
       FROM focus_sessions fs
       LEFT JOIN todo_items ti ON fs.todo_id = ti.id
       LEFT JOIN tasks t ON ti.task_id = t.id
       WHERE fs.date = ? AND fs.status = 'completed'
       ORDER BY fs.started_at`,
      [date]
    ) as Array<Record<string, unknown>>

    // Get todo items for the date
    const todos = db.all(
      `SELECT ti.*, t.title as task_title, t.color as task_color
       FROM todo_items ti
       LEFT JOIN tasks t ON ti.task_id = t.id
       WHERE ti.date = ?
       ORDER BY ti.sort_order`,
      [date]
    ) as Array<Record<string, unknown>>

    // Calculate total focus time
    let total_focus_sec = 0
    for (const s of sessions)
    {
      total_focus_sec += (s.actual_duration_sec as number) || 0
    }
    const total_min = Math.floor(total_focus_sec / 60)
    const hours = Math.floor(total_min / 60)
    const mins = total_min % 60

    // Build markdown
    let md = `# 📔 Diary - ${date}\n\n`

    // Summary
    md += `## 📊 今日统计\n\n`
    md += `- **总专注时间**: ${hours} 小时 ${mins} 分钟\n`
    md += `- **专注会话数**: ${sessions.length}\n`
    md += `- **完成任务数**: ${todos.filter((t) => t.status === 'done').length} / ${todos.length}\n\n`

    // Focus sessions
    if (sessions.length > 0)
    {
      md += `## 🎯 专注会话\n\n`
      md += `| 主题 | 计划时长 | 实际时长 | 开始时间 |\n`
      md += `|------|----------|----------|----------|\n`
      for (const s of sessions)
      {
        const actual_min = Math.floor((s.actual_duration_sec as number || 0) / 60)
        md += `| ${s.display_subject || '未命名'} | ${s.planned_duration_min} 分钟 | ${actual_min} 分钟 | ${(s.started_at as string).slice(11, 19)} |\n`
      }
      md += `\n`
    }

    // Tasks
    md += `## ✅ 任务状态\n\n`
    const done_tasks = todos.filter((t) => t.status === 'done')
    const pending_tasks = todos.filter((t) => t.status === 'pending')

    if (done_tasks.length > 0)
    {
      md += `### 已完成\n\n`
      for (const t of done_tasks)
      {
        md += `- [x] ${t.custom_title || t.task_title || '未命名任务'}\n`
      }
      md += `\n`
    }

    if (pending_tasks.length > 0)
    {
      md += `### 未完成\n\n`
      for (const t of pending_tasks)
      {
        md += `- [ ] ${t.custom_title || t.task_title || '未命名任务'}\n`
      }
      md += `\n`
    }

    if (todos.length === 0)
    {
      md += `今日没有添加任务。\n\n`
    }

    // Self reflection placeholder
    md += `## 💭 自我反思\n\n`
    md += `*(在此写下你今天的思考和感悟...)*\n\n`
    md += `---\n\n`
    md += `<sub>Generated by MoeFocus 🌸</sub>\n`

    // Save to file
    const sums_dir = join(app.getPath('userData'), 'sums')
    if (!existsSync(sums_dir))
    {
      mkdirSync(sums_dir, { recursive: true })
    }

    const file_name = `${date}.md`
    const file_path = join(sums_dir, file_name)
    writeFileSync(file_path, md, 'utf-8')

    // Update diary_entries in DB
    const existing = db.get('SELECT id FROM diary_entries WHERE date = ?', [date])
    if (existing)
    {
      db.run(
        "UPDATE diary_entries SET summary_text = ?, file_path = ?, updated_at = datetime('now') WHERE date = ?",
        [md, file_path, date]
      )
    }
    else
    {
      db.run(
        'INSERT INTO diary_entries (date, summary_text, file_path) VALUES (?, ?, ?)',
        [date, md, file_path]
      )
    }

    return { file_path, content: md }
  }

  static get_content(date: string): string | null
  {
    const db = DatabaseService.instance
    const entry = db.get(
      'SELECT summary_text, reflection_text FROM diary_entries WHERE date = ?',
      [date]
    ) as Record<string, unknown> | undefined

    if (!entry) return null

    let content = (entry.summary_text as string) || ''
    if (entry.reflection_text)
    {
      content += `\n\n## ✍️ 补充反思\n\n${entry.reflection_text}\n`
    }
    return content
  }
}
