// ===== Phase 4: 日记自动生成服务 =====
// 查询当日 focus_sessions + todo_items → 生成 Markdown 模板
// 保存到 %APPDATA%/moefocus/sums/YYYY-MM-DD.md
// Phase 5: 配合 GitService 自动 commit+push

import { DatabaseService } from './DatabaseService'
import { join } from 'path'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { app } from 'electron'

export class DiaryService
{
  static generate(date: string): { file_path: string; content: string }
  {
    const db = DatabaseService.instance

    // Get completed focus sessions for the date
    const sessions = db.all(
      `SELECT fs.*, COALESCE(t.title, fs.subject) as display_subject
       FROM focus_sessions fs
       LEFT JOIN todo_items ti ON fs.todo_id = ti.id
       LEFT JOIN tasks t ON ti.task_id = t.id
       WHERE fs.date = ? AND fs.status = 'completed'
       ORDER BY fs.started_at`,
      [date]
    ) as Array<Record<string, unknown>>

    // Calculate total focus time
    let total_focus_sec = 0
    const subject_times: Record<string, number> = {}
    for (const s of sessions)
    {
      const sec = (s.actual_duration_sec as number) || 0
      total_focus_sec += sec
      const label = (s.display_subject as string) || '未命名'
      subject_times[label] = (subject_times[label] || 0) + sec
    }
    const total_min = Math.floor(total_focus_sec / 60)
    const hours = Math.floor(total_min / 60)
    const mins = total_min % 60

    // Build markdown
    let md = `# 📔 Diary - ${date}\n\n`

    // Summary
    md += `## 📊 今日统计\n\n`
    md += `- **总专注时间**: ${hours} 小时 ${mins} 分钟\n`
    md += `- **专注会话数**: ${sessions.length}\n\n`

    // Per-subject breakdown
    if (Object.keys(subject_times).length > 0)
    {
      md += `## 🎯 事项时间分布\n\n`
      const sorted = Object.entries(subject_times).sort((a, b) => b[1] - a[1])
      for (const [subject, sec] of sorted)
      {
        const m = Math.floor(sec / 60)
        const h = Math.floor(m / 60)
        const remaining_m = m % 60
        const time_str = h > 0 ? `${h}h ${remaining_m}m` : `${remaining_m}m`
        md += `- **${subject}**: ${time_str}\n`
      }
      md += `\n`
    }
    else
    {
      md += `今日没有专注记录。\n\n`
    }

    // Self reflection placeholder
    md += `## 💭 自我反思\n\n`
    md += `*(在此写下你今天的思考和感悟...)*\n\n`
    md += `---\n\n`
    md += `<sub>Generated by MoeFocus 🌸</sub>\n`

    // Save to file
    const sums_dir = join(app.getPath('userData'), 'sums')
    if (!existsSync(sums_dir))
    {
      mkdirSync(sums_dir, { recursive: true })
    }

    const file_name = `${date}.md`
    const file_path = join(sums_dir, file_name)
    writeFileSync(file_path, md, 'utf-8')

    // Update diary_entries in DB
    const existing = db.get('SELECT id FROM diary_entries WHERE date = ?', [date])
    if (existing)
    {
      db.run(
        "UPDATE diary_entries SET summary_text = ?, file_path = ?, updated_at = datetime('now') WHERE date = ?",
        [md, file_path, date]
      )
    }
    else
    {
      db.run(
        'INSERT INTO diary_entries (date, summary_text, file_path) VALUES (?, ?, ?)',
        [date, md, file_path]
      )
    }

    return { file_path, content: md }
  }

  static get_content(date: string): string | null
  {
    const db = DatabaseService.instance
    const entry = db.get(
      'SELECT summary_text, reflection_text FROM diary_entries WHERE date = ?',
      [date]
    ) as Record<string, unknown> | undefined

    if (!entry) return null

    let content = (entry.summary_text as string) || ''
    if (entry.reflection_text)
    {
      content += `\n\n## ✍️ 补充反思\n\n${entry.reflection_text}\n`
    }
    return content
  }
}
