// ===== Phase 4: 日记自动生成服务 =====
// 查询当日 focus_sessions + todo_items → 生成 Markdown 模板
// 保存到 %APPDATA%/moefocus/sums/YYYY-MM-DD.md
// Phase 5: 配合 GitService 自动 commit+push

import { DatabaseService } from './DatabaseService'
import { join } from 'path'
import { writeFileSync, readFileSync, existsSync, mkdirSync, copyFileSync } from 'fs'
import { app } from 'electron'
import { extract_diary_reflection, get_cleared_reflection, replace_diary_reflection } from './SyncService'

export class DiaryService
{
  private static readonly reflection_placeholder = '*(在此写下你今天的思考和感悟...)*'
  private static readonly generated_start_marker = '<!-- moe:generated:start -->'
  private static readonly generated_end_marker = '<!-- moe:generated:end -->'

  private static backup_existing_file(file_path: string): void
  {
    if (!existsSync(file_path)) return

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
    copyFileSync(file_path, `${file_path}.${timestamp}.bak`)
  }

  private static normalize_content(content: string): string
  {
    return content.replace(/\r\n/g, '\n')
  }

  private static build_manual_section(existing_content: string, date: string): string
  {
    const normalized = DiaryService.normalize_content(existing_content).trim()
    if (!normalized)
    {
      return `## 💭 自我反思\n\n${DiaryService.reflection_placeholder}\n\n---\n\n<sub>Generated by MoeFocus 🌸</sub>\n`
    }

    const reflection_start = normalized.indexOf('## 💭 自我反思')
    if (reflection_start !== -1)
    {
      const manual_section = normalized.slice(reflection_start).trim()
      return `${manual_section}\n`
    }

    const expected_title = `# 📔 Diary - ${date}`
    const stats_start = normalized.indexOf('## 📊 今日统计')
    if (stats_start !== -1)
    {
      const prefix = normalized.slice(0, stats_start).trim()
      const preserved_prefix = prefix && prefix !== expected_title
        ? `\n\n## 📝 旧文件保留内容\n\n${prefix}`
        : ''

      return [
        '## 💭 自我反思',
        '',
        DiaryService.reflection_placeholder,
        preserved_prefix,
        '',
        '---',
        '',
        '<sub>Generated by MoeFocus 🌸</sub>',
        ''
      ].join('\n')
    }

    return [
      '## 💭 自我反思',
      '',
      normalized,
      '',
      '---',
      '',
      '<sub>Generated by MoeFocus 🌸</sub>',
      ''
    ].join('\n')
  }

  private static merge_generated_content(existing_content: string, generated_content: string, date: string): string
  {
    const normalized_existing = DiaryService.normalize_content(existing_content)
    if (!normalized_existing.trim())
    {
      const manual_section = DiaryService.build_manual_section('', date)
      return `${generated_content.trimEnd()}\n\n${manual_section.trimEnd()}\n`
    }

    const generated_start = normalized_existing.indexOf(DiaryService.generated_start_marker)
    const generated_end = normalized_existing.indexOf(DiaryService.generated_end_marker)
    if (generated_start !== -1 && generated_end !== -1 && generated_end > generated_start)
    {
      const manual_section = normalized_existing
        .slice(generated_end + DiaryService.generated_end_marker.length)
        .replace(/^\s+/, '')
      return `${generated_content.trimEnd()}\n\n${manual_section.trimEnd()}\n`
    }

    const manual_section = DiaryService.build_manual_section(normalized_existing, date)
    return `${generated_content.trimEnd()}\n\n${manual_section.trimEnd()}\n`
  }

  static generate(date: string): { file_path: string; content: string }
  {
    const db = DatabaseService.instance

    // Get completed focus sessions for the date
    const sessions = db.all(
      `SELECT fs.*, COALESCE(t.title, fs.subject) as display_subject
       FROM focus_sessions fs
       LEFT JOIN todo_items ti ON fs.todo_id = ti.id
       LEFT JOIN tasks t ON ti.task_id = t.id
       WHERE fs.date = ? AND fs.status = 'completed'
       ORDER BY fs.started_at`,
      [date]
    ) as Array<Record<string, unknown>>

    // Calculate total focus time
    let total_focus_sec = 0
    const subject_times: Record<string, number> = {}
    for (const s of sessions)
    {
      const sec = (s.actual_duration_sec as number) || 0
      total_focus_sec += sec
      const label = (s.display_subject as string) || '未命名'
      subject_times[label] = (subject_times[label] || 0) + sec
    }
    const total_min = Math.floor(total_focus_sec / 60)
    const hours = Math.floor(total_min / 60)
    const mins = total_min % 60

    let generated_md = `${DiaryService.generated_start_marker}\n`
    generated_md += `# 📔 Diary - ${date}\n\n`

    // Summary
    generated_md += `## 📊 今日统计\n\n`
    generated_md += `- **总专注时间**: ${hours} 小时 ${mins} 分钟\n`
    generated_md += `- **专注会话数**: ${sessions.length}\n\n`

    // Per-subject breakdown
    if (Object.keys(subject_times).length > 0)
    {
      generated_md += `## 🎯 事项时间分布\n\n`
      const sorted = Object.entries(subject_times).sort((a, b) => b[1] - a[1])
      for (const [subject, sec] of sorted)
      {
        const m = Math.floor(sec / 60)
        const h = Math.floor(m / 60)
        const remaining_m = m % 60
        const time_str = h > 0 ? `${h}h ${remaining_m}m` : `${remaining_m}m`
        generated_md += `- **${subject}**: ${time_str}\n`
      }
      generated_md += `\n`
    }
    else
    {
      generated_md += `今日没有专注记录。\n\n`
    }

    generated_md += `${DiaryService.generated_end_marker}\n\n`

    // Save to file
    const sums_dir = join(app.getPath('userData'), 'sums')
    if (!existsSync(sums_dir))
    {
      mkdirSync(sums_dir, { recursive: true })
    }

    const file_name = `${date}.md`
    const file_path = join(sums_dir, file_name)
    const existing_content = existsSync(file_path)
      ? readFileSync(file_path, 'utf-8')
      : ''
    let md = DiaryService.merge_generated_content(existing_content, generated_md, date)
    const existing_reflection = existing_content ? extract_diary_reflection(existing_content) : ''
    const merged_reflection = extract_diary_reflection(md)
    if (existing_reflection && !merged_reflection)
    {
      md = md.replace(DiaryService.reflection_placeholder, existing_reflection)
    }

    if (md !== DiaryService.normalize_content(existing_content))
    {
      DiaryService.backup_existing_file(file_path)
      writeFileSync(file_path, md, 'utf-8')
    }

    // Update diary_entries in DB
    const existing = db.get('SELECT id FROM diary_entries WHERE date = ?', [date])
    if (existing)
    {
      db.run(
        "UPDATE diary_entries SET summary_text = ?, file_path = ?, updated_at = datetime('now') WHERE date = ?",
        [md, file_path, date]
      )
    }
    else
    {
      db.run(
        'INSERT INTO diary_entries (date, summary_text, file_path) VALUES (?, ?, ?)',
        [date, md, file_path]
      )
    }

    return { file_path, content: md }
  }

  static get_content(date: string): string | null
  {
    const db = DatabaseService.instance
    const entry = db.get(
      'SELECT summary_text, reflection_text FROM diary_entries WHERE date = ?',
      [date]
    ) as Record<string, unknown> | undefined

    if (!entry) return null

    let content = (entry.summary_text as string) || ''
    if (entry.reflection_text)
    {
      content += `\n\n## ✍️ 补充反思\n\n${entry.reflection_text}\n`
    }
    return content
  }

  static clear_manual_content(date: string): { success: boolean; file_path?: string; error?: string }
  {
    const db = DatabaseService.instance
    const sums_dir = join(app.getPath('userData'), 'sums')
    const file_path = join(sums_dir, `${date}.md`)
    const entry = db.get(
      'SELECT summary_text, file_path FROM diary_entries WHERE date = ?',
      [date]
    ) as { summary_text?: string; file_path?: string } | undefined

    const target_file_path = entry?.file_path || file_path
    const existing_content = existsSync(target_file_path)
      ? readFileSync(target_file_path, 'utf-8')
      : entry?.summary_text || ''

    if (!existing_content)
    {
      return { success: false, error: `${date} 没有可清空的日记内容` }
    }

    let updated_content = replace_diary_reflection(existing_content, get_cleared_reflection())
    if (updated_content === existing_content && !existing_content.includes('## 💭 自我反思'))
    {
      updated_content = `${existing_content.trimEnd()}\n\n## 💭 自我反思\n\n${get_cleared_reflection()}\n`
    }

    if (!existsSync(sums_dir))
    {
      mkdirSync(sums_dir, { recursive: true })
    }

    DiaryService.backup_existing_file(target_file_path)
    writeFileSync(target_file_path, updated_content, 'utf-8')

    if (entry)
    {
      db.run(
        "UPDATE diary_entries SET summary_text = ?, reflection_text = '', file_path = ?, updated_at = datetime('now') WHERE date = ?",
        [updated_content, target_file_path, date]
      )
    }
    else
    {
      db.run(
        'INSERT INTO diary_entries (date, summary_text, reflection_text, file_path) VALUES (?, ?, ?, ?)',
        [date, updated_content, '', target_file_path]
      )
    }

    return { success: true, file_path: target_file_path }
  }
}
