// ===== 安全桥接层 — 所有主进程能力通过此文件暴露 =====
// Phase 1: 窗口控制 + 文件系统操作
// Phase 2: tasks/todos CRUD (拖拽依赖的 API)
// Phase 3: focus 会话控制 + 实时 tick 事件监听
// Phase 4: diary 日记生成与反思保存
// Phase 5: git 同步 (commit/push/pull) + email 发送
// Phase 6: stats 统计聚合查询
// Phase 8: settings 设置读写 + 变更监听

import { contextBridge, ipcRenderer } from 'electron'

const electron_api = {
  tasks:
  {
    get_all: () => ipcRenderer.invoke('task:getAll'),
    create: (task: TaskInput) => ipcRenderer.invoke('task:create', task),
    update: (id: number, data: Partial<TaskInput>) => ipcRenderer.invoke('task:update', id, data),
    remove: (id: number) => ipcRenderer.invoke('task:delete', id)
  },
  todos:
  {
    get_by_date: (date: string) => ipcRenderer.invoke('todo:getByDate', date),
    add: (item: TodoInput) => ipcRenderer.invoke('todo:add', item),
    update: (id: number, data: Partial<TodoInput>) => ipcRenderer.invoke('todo:update', id, data),
    remove: (id: number) => ipcRenderer.invoke('todo:remove', id),
    reorder: (ids: number[]) => ipcRenderer.invoke('todo:reorder', ids)
  },
  focus:
  {
    start: (session: FocusInput) => ipcRenderer.invoke('focus:start', session),
    pause: (id: number) => ipcRenderer.invoke('focus:pause', id),
    resume: (id: number) => ipcRenderer.invoke('focus:resume', id),
    complete: (id: number, actual_sec: number) => ipcRenderer.invoke('focus:complete', id, actual_sec),
    abandon: (id: number) => ipcRenderer.invoke('focus:abandon', id),
    get_current: () => ipcRenderer.invoke('focus:getCurrent'),
    get_by_date: (date: string) => ipcRenderer.invoke('focus:getByDate', date),
    on_tick: (cb: (remaining: number) => void) =>
    {
      const listener = (_event: Electron.IpcRendererEvent, remaining: number) => cb(remaining)
      ipcRenderer.on('focus:tick', listener)
      return () => ipcRenderer.removeListener('focus:tick', listener)
    },
    on_session_end: (cb: () => void) =>
    {
      const listener = () => cb()
      ipcRenderer.on('focus:sessionEnd', listener)
      return () => ipcRenderer.removeListener('focus:sessionEnd', listener)
    }
  },
  diary:
  {
    generate: (date: string) => ipcRenderer.invoke('diary:generate', date),
    get_by_date: (date: string) => ipcRenderer.invoke('diary:getByDate', date),
    save_reflection: (date: string, text: string) => ipcRenderer.invoke('diary:saveReflection', date, text),
    list_all: () => ipcRenderer.invoke('diary:listAll'),
    on_auto_generated: (cb: (date: string) => void) =>
    {
      const listener = (_event: Electron.IpcRendererEvent, date: string) => cb(date)
      ipcRenderer.on('diary:autoGenerated', listener)
      return () => ipcRenderer.removeListener('diary:autoGenerated', listener)
    }
  },
  stats:
  {
    get_weekly: (week_start: string) => ipcRenderer.invoke('stats:getWeekly', week_start),
    get_monthly: (month: string) => ipcRenderer.invoke('stats:getMonthly', month),
    get_focus_items: (start_date: string, end_date: string) =>
      ipcRenderer.invoke('stats:getFocusItems', start_date, end_date)
  },
  settings:
  {
    get: (key: string) => ipcRenderer.invoke('settings:get', key),
    get_all: () => ipcRenderer.invoke('settings:getAll'),
    set: (key: string, value: unknown) => ipcRenderer.invoke('settings:set', key, value),
    on_changed: (cb: (data: { key: string; value: unknown }) => void) =>
    {
      const listener = (_event: Electron.IpcRendererEvent, data: { key: string; value: unknown }) => cb(data)
      ipcRenderer.on('settings:changed', listener)
      return () => ipcRenderer.removeListener('settings:changed', listener)
    }
  },
  git:
  {
    get_status: () => ipcRenderer.invoke('git:getStatus'),
    commit: (message: string) => ipcRenderer.invoke('git:commit', message),
    push: () => ipcRenderer.invoke('git:push'),
    pull: () => ipcRenderer.invoke('git:pull'),
    set_remote: (url: string) => ipcRenderer.invoke('git:setRemote', url),
    get_remote: () => ipcRenderer.invoke('git:getRemote'),
    init_repo: () => ipcRenderer.invoke('git:initRepo')
  },
  email:
  {
    send: (to: string, subject: string, body: string) => ipcRenderer.invoke('email:send', to, subject, body),
    send_reminder: (date: string) => ipcRenderer.invoke('email:sendReminder', date),
    test_connection: (user: string, pass: string) => ipcRenderer.invoke('email:testConnection', user, pass)
  },
  file:
  {
    open_in_typora: (file_path: string) => ipcRenderer.invoke('file:openInTypora', file_path),
    pick_image: () => ipcRenderer.invoke('file:pickImage'),
    set_wallpaper: (file_path: string) => ipcRenderer.invoke('file:setWallpaper', file_path),
    on_file_drop: (cb: (file_path: string) => void) =>
    {
      const listener = (_event: Electron.IpcRendererEvent, file_path: string) => cb(file_path)
      ipcRenderer.on('file:dropped', listener)
      return () => ipcRenderer.removeListener('file:dropped', listener)
    }
  },
  window:
  {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close'),
    is_maximized: () => ipcRenderer.invoke('window:isMaximized')
  }
}

contextBridge.exposeInMainWorld('electronAPI', electron_api)

// Type declarations for renderer
interface TaskInput
{
  title: string
  category?: string
  icon?: string
  color?: string
  sort_order?: number
  is_active?: number
}

interface TodoInput
{
  task_id?: number
  custom_title?: string
  date: string
  status?: string
  sort_order?: number
}

interface FocusInput
{
  todo_id?: number
  subject: string
  planned_duration_min: number
  rest_duration_sec?: number
  date: string
}

export type { TaskInput, TodoInput, FocusInput }
